import { memo, useEffect, useRef } from "react";
import type { BrowserStudentRow } from "@/lib/student-records/contracts";
import { countCharacters, targetLengthRange, targetLengthStatus, utf8ByteLength } from "@/lib/student-records/metrics";

export function autoGrowResultTextarea(textarea: HTMLTextAreaElement) { textarea.style.height = "auto"; textarea.style.height = `${textarea.scrollHeight}px`; }

export const StudentResultRow = memo(function StudentResultRow({ row, targetLength, similarity, error, disabled, onChange, hideStudentName = false }: { row: BrowserStudentRow; targetLength: number; similarity: number; error?: string; disabled: boolean; hideStudentName?: boolean; onChange: (rowId: string, field: "generatedText" | "teacherMemo" | "useInExport", value: string | boolean) => void }) {
  const resultRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (resultRef.current) autoGrowResultTextarea(resultRef.current); }, [row.generatedText]);
  const range = targetLengthRange(targetLength);
  const status = targetLengthStatus(row.generatedText, targetLength);
  const statusLabel = status === "short" ? "목표보다 짧음" : status === "long" ? "목표보다 김" : "적정 길이";
  return <tr className="border-t border-neutral-200"><td className="p-2 text-center text-sm text-neutral-900">{row.studentNumber}</td>{!hideStudentName ? <td className="p-2 text-sm text-neutral-900">{row.studentName || "이름 미입력"}</td> : null}<td className="p-2"><label className="sr-only" htmlFor={`${row.rowId}-result`}>생성 문구</label><textarea ref={resultRef} id={`${row.rowId}-result`} rows={4} value={row.generatedText} disabled={disabled} aria-disabled={disabled} onChange={(event) => { autoGrowResultTextarea(event.currentTarget); onChange(row.rowId, "generatedText", event.target.value); }} className="min-h-24 w-80 resize-y overflow-hidden rounded border border-neutral-300 bg-white p-2 text-sm leading-6 text-neutral-900 disabled:bg-neutral-100 disabled:text-neutral-700" /><p className="mt-1 text-xs text-neutral-600">{countCharacters(row.generatedText)}자 · {utf8ByteLength(row.generatedText)} bytes</p><p className="text-xs text-neutral-700">목표 범위: {range.min}~{range.max}자 · {statusLabel}</p>{error ? <p className="text-xs text-red-700">생성 오류: {error}</p> : null}</td><td className="p-2 text-sm text-neutral-800">{similarity >= 80 ? `검토 필요 (${similarity}%)` : `일반 (${similarity}%)`}</td><td className="p-2"><label className="sr-only" htmlFor={`${row.rowId}-memo`}>교사 메모</label><textarea id={`${row.rowId}-memo`} value={row.teacherMemo} disabled={disabled} aria-disabled={disabled} onChange={(event) => onChange(row.rowId, "teacherMemo", event.target.value)} className="min-h-16 w-48 rounded border border-neutral-300 bg-white p-2 text-sm text-neutral-900 disabled:bg-neutral-100 disabled:text-neutral-700" /></td><td className="p-2 text-center"><input aria-label={`${row.studentNumber}번 내보내기 사용`} type="checkbox" checked={row.useInExport} disabled={disabled} aria-disabled={disabled} onChange={(event) => onChange(row.rowId, "useInExport", event.target.checked)} /></td></tr>;
});
