import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

const base = process.env.Q2_B11_BASE_URL; const token = process.env.Q2_BROWSER_FIXTURE_TOKEN; const auth = { "x-q2-browser-fixture-token": token };
const telemetry = { viewports: [], audits: { responsive: [], semantics: [], keyboard: [], reducedMotion: [] }, console: [], responses: [], pageErrors: [], failedRequests: [], duplicateKeyWarnings: [], screenshots: [], hydrationMismatchCount: 0 };
const viewports = [["desktop", 1440, 900], ["small-desktop", 1280, 720], ["tablet-landscape", 1024, 768], ["tablet-portrait", 768, 1024], ["mobile", 390, 844], ["narrow-mobile", 360, 800]];
function track(page, label) { page.on("console", (m) => { if (m.type() === "error") telemetry.console.push({ label, type: m.type(), text: m.text() }); if (/hydration|server rendered HTML/i.test(m.text())) telemetry.hydrationMismatchCount += 1; if (/unique.*key|duplicate.*key/i.test(m.text())) telemetry.duplicateKeyWarnings.push({ label, text: m.text() }); }); page.on("response", (r) => { const url = new URL(r.url()); if (url.origin === base && r.status() >= 400) telemetry.responses.push({ label, path: url.pathname, status: r.status() }); }); page.on("pageerror", (e) => telemetry.pageErrors.push({ label, message: e.message })); page.on("requestfailed", (r) => telemetry.failedRequests.push({ label, path: new URL(r.url()).pathname, failure: r.failure()?.errorText ?? "unknown" })); }
async function fixture(context, label) { await context.route("**/*", (route) => { const url = new URL(route.request().url()); if (url.origin !== base) return route.fulfill({ status: 204, body: "" }); if (url.pathname === "/api/v1/me/ui-prefs") return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ classPrefs: {} }) }); if (url.pathname === "/api/v1/dashboard/student-apps/session") return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, session: null }) }); return route.continue({ headers: { ...route.request().headers(), ...auth, "x-q2-browser-client-label": label } }); }); }
async function reset(page) { expect((await page.request.post(`${base}/api/q2/browser/multi-user-polling-fixture/reset`, { headers: auth })).status()).toBe(200); }
async function seed(page) { await page.goto(`${base}/s/q2b10a`); await expect(page.getByTestId("student-smart-layer")).toBeVisible(); for (const text of ["긴 한국어 카드 내용입니다. 학생이 읽고 답할 수 있도록 여러 문장으로 구성한 검증용 내용입니다.", "https://example.invalid/this-is-a-long-url-without-natural-breaks-for-responsive-layout-verification", "붙여쓰기없는긴문자열반응형레이아웃검증콘텐츠", "여러 줄\n텍스트도 카드 안에서 안전하게 보여야 합니다."]) { await page.keyboard.press("n"); const field = page.getByTestId("student-card-composer-text"); await field.fill(text); await page.getByTestId("student-card-composer-submit").click(); await expect(field).toHaveCount(0); } }
async function openTeacher(page) { const url = `${base}/dashboard/boards/00000000-0000-4000-8000-0000000000ba/board`; for (let attempt = 0; attempt < 2; attempt += 1) { try { await page.goto(url, { waitUntil: "domcontentloaded" }); await expect(page.locator("[data-card-id]").first()).toBeVisible(); return; } catch (error) { if (attempt) throw error; } } }
async function auditLayout(page, screen, name, width, height) { await page.setViewportSize({ width, height }); await page.waitForTimeout(120); const result = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth, main: Boolean(document.querySelector("main")), buttons: [...document.querySelectorAll("button")].filter((node) => { const r = node.getBoundingClientRect(); return r.width > 0 && r.height > 0; }).map((node) => ({ name: node.getAttribute("aria-label") || node.textContent?.trim() || "", fixed: getComputedStyle(node).position === "fixed", offscreen: (() => { const r = node.getBoundingClientRect(); return r.right < 0 || r.left > innerWidth || r.bottom < 0 || r.top > innerHeight; })() })) })); expect(result.scrollWidth).toBeLessThanOrEqual(result.clientWidth + 1); expect(result.main).toBe(true); expect(result.buttons.filter((b) => !b.name).length).toBe(0); telemetry.audits.responsive.push({ screen, viewport: name, ...result, criticalOffscreen: result.buttons.filter((b) => b.fixed && b.offscreen).length }); telemetry.viewports.push({ screen, name, width, height, scrollWidth: result.scrollWidth, clientWidth: result.clientWidth }); }
async function shot(page, name) { const file = `${process.env.Q2_B11_SCREENSHOT_DIR}/${name}.png`; await fs.mkdir(process.env.Q2_B11_SCREENSHOT_DIR, { recursive: true }); await page.screenshot({ path: file, fullPage: false }); telemetry.screenshots.push(file); }

test.afterAll(async () => { await fs.writeFile(process.env.Q2_B11_TELEMETRY_PATH, `${JSON.stringify(telemetry, null, 2)}\n`); });

test("student responsive matrix, themes, and long content", async ({ browser }) => { const context = await browser.newContext(); await fixture(context, "student"); const page = await context.newPage(); track(page, "student"); try { await reset(page); await seed(page); for (const [name, width, height] of viewports) { await auditLayout(page, "student", name, width, height); } await page.setViewportSize({ width: 390, height: 844 }); await shot(page, "student-mobile"); const own = page.locator("[data-card-id]").first().getByTestId("student-owned-card-menu-trigger"); await expect(own).toBeVisible(); await own.click(); await expect(page.getByRole("menu")).toBeVisible(); await shot(page, "student-mobile-menu"); await page.keyboard.press("Escape"); await expect(page.getByRole("menu")).toHaveCount(0); await page.setViewportSize({ width: 1440, height: 900 }); await shot(page, "student-desktop"); } finally { await context.close(); } });

test("teacher responsive matrix and tablet visibility operation", async ({ browser }) => { const context = await browser.newContext(); await fixture(context, "teacher"); const seedPage = await context.newPage(); track(seedPage, "teacher-seed"); await reset(seedPage); await seed(seedPage); await seedPage.close(); const page = await context.newPage(); track(page, "teacher"); try { await openTeacher(page); for (const [name, width, height] of viewports) await auditLayout(page, "teacher", name, width, height); await page.setViewportSize({ width: 768, height: 1024 }); const card = page.locator("[data-card-id]").first(); await card.getByRole("button", { name: "카드 메뉴 열기" }).click(); await expect(page.getByRole("menuitem", { name: "학생에게 숨기기" })).toBeVisible(); await shot(page, "teacher-tablet-menu"); await page.getByRole("menuitem", { name: "학생에게 숨기기" }).click(); await card.getByRole("button", { name: "카드 메뉴 열기" }).click(); await page.getByRole("menuitem", { name: "학생에게 공개하기" }).click(); await page.setViewportSize({ width: 1440, height: 900 }); await shot(page, "teacher-desktop"); } finally { await context.close(); } });

test("keyboard-only student journey returns focus after Escape", async ({ browser }) => { const context = await browser.newContext(); await fixture(context, "keyboard-student"); const page = await context.newPage(); track(page, "keyboard-student"); try { await reset(page); await seed(page); await page.setViewportSize({ width: 390, height: 844 }); await page.keyboard.press("n"); const field = page.getByTestId("student-card-composer-text"); await expect(field).toBeFocused(); await page.keyboard.type("키보드 제출 카드"); await page.getByTestId("student-card-composer-submit").focus(); await page.keyboard.press("Enter"); await expect(field).toHaveCount(0); const trigger = page.locator("[data-card-id]").last().getByTestId("student-owned-card-menu-trigger"); await trigger.focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("menu")).toBeVisible(); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); telemetry.audits.keyboard.push({ screen: "student", submit: "PASS", menuEscapeFocusReturn: "PASS" }); await shot(page, "student-keyboard-focus"); } finally { await context.close(); } });

test("keyboard-only teacher journey exposes menu semantics", async ({ browser }) => { const context = await browser.newContext(); await fixture(context, "keyboard-teacher"); const seedPage = await context.newPage(); track(seedPage, "keyboard-teacher-seed"); await reset(seedPage); await seed(seedPage); await seedPage.close(); const page = await context.newPage(); track(page, "keyboard-teacher"); try { await openTeacher(page); const trigger = page.locator("[data-card-id]").first().getByRole("button", { name: "카드 메뉴 열기" }); await trigger.focus(); await page.keyboard.press("Enter"); const item = page.getByRole("menuitem", { name: "학생에게 숨기기" }); await expect(item).toBeVisible(); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); telemetry.audits.keyboard.push({ screen: "teacher", menuRole: "PASS", escapeFocusReturn: "PASS" }); } finally { await context.close(); } });

test("semantic audit and reduced motion retain usable controls", async ({ browser }) => { const context = await browser.newContext({ reducedMotion: "reduce" }); await fixture(context, "semantics"); const page = await context.newPage(); track(page, "semantics"); try { await reset(page); await seed(page); const scan = await page.evaluate(() => { const visible = (node) => { const style = getComputedStyle(node); const rect = node.getBoundingClientRect(); return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0; }; return { unnamedButtons: [...document.querySelectorAll("button")].filter((b) => visible(b) && !(b.getAttribute("aria-label") || b.textContent?.trim())).length, unnamedControls: [...document.querySelectorAll("input, textarea")].filter((n) => visible(n) && !(n.getAttribute("aria-label") || n.getAttribute("aria-labelledby") || n.labels?.length)).length, duplicateIds: [...document.querySelectorAll("[id]")].map((n) => n.id).filter((id, index, all) => all.indexOf(id) !== index).length, main: Boolean(document.querySelector("main")), h1: document.querySelectorAll("h1").length }; }); expect(scan.unnamedButtons).toBe(0); expect(scan.unnamedControls).toBe(0); expect(scan.duplicateIds).toBe(0); expect(scan.main).toBe(true); expect(scan.h1).toBeLessThanOrEqual(1); telemetry.audits.semantics.push(scan); telemetry.audits.reducedMotion.push({ screen: "student", result: "PASS" }); await shot(page, "reduced-motion"); } finally { await context.close(); } });
