import { test, expect } from "@playwright/test";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { readStoredZip } from "../../scripts/qa/lib/read-stored-zip.mjs";
const base = process.env.Q2_B8_BASE_URL; const token = process.env.Q2_BROWSER_FIXTURE_TOKEN; const out = process.env.Q2_B8_SUMMARY_DIR; const boardId = "00000000-0000-4000-8000-0000000000b8";
const auth = () => ({ "x-q2-browser-fixture-token": token });
const atomicWrite = async (file, value) => { const temp = `${file}.${process.pid}.${Date.now()}.tmp`; await fs.writeFile(temp, value); await fs.rename(temp, file); };
async function writeEvidence(id, evidence) { await fs.mkdir(out, { recursive: true }); await atomicWrite(path.join(out, `scenario-${id}.json`), `${JSON.stringify({ schemaVersion: 1, workId: "Q2-B8", scenarioId: id, status: "passed", startedAt: new Date().toISOString(), finishedAt: new Date().toISOString(), ...evidence }, null, 2)}\n`); }
async function reset(page) { expect((await page.request.post(`${base}/api/q2/browser/result-download-fixture/reset`, { headers: auth() })).status()).toBe(200); }
async function openBackup(page) { await page.goto(`${base}/dashboard/boards/${boardId}/board`, { waitUntil: "domcontentloaded" }); await expect(page.getByRole("heading", { name: "B8 결과 백업" })).toBeVisible(); const railRoot = page.getByTestId("canonical-right-rail"); await expect(railRoot).toBeAttached(); await expect(railRoot).toHaveAttribute("data-board-rail-client-ready", "true"); const trigger = page.locator('button[aria-controls="canonical-right-rail-panel"]'); const visibleTriggers = await trigger.evaluateAll((buttons) => buttons.filter((button) => { const style = window.getComputedStyle(button); const box = button.getBoundingClientRect(); return style.visibility !== "hidden" && style.display !== "none" && box.width > 0 && box.height > 0; }).length); expect(visibleTriggers).toBe(1); await expect(trigger).toHaveCount(1); await expect(trigger).toBeVisible(); await expect(trigger).toBeEnabled(); if (await trigger.getAttribute("aria-expanded") === "false") await trigger.click(); await expect(trigger).toHaveAttribute("aria-expanded", "true"); const rail = page.getByTestId("canonical-right-rail-panel"); await expect(rail).toBeVisible(); await expect(rail).toHaveAttribute("data-state", "open"); await rail.getByRole("button", { name: "설정", exact: true }).click(); await expect(page.getByRole("region", { name: "보드 백업" })).toBeVisible(); }
async function instrument(page, failOnce = false) { await page.addInitScript((initialFail) => { const create = URL.createObjectURL.bind(URL); const revoke = URL.revokeObjectURL.bind(URL); let failed = false; window.__q2B8BlobMeta = { type: null, size: 0, createCount: 0, revokeCount: 0 }; URL.createObjectURL = (blob) => { window.__q2B8BlobMeta.createCount += 1; if (initialFail && !failed) { failed = true; throw new Error("q2-b8-create-object-url"); } window.__q2B8BlobMeta.type = blob.type; window.__q2B8BlobMeta.size = blob.size; return create(blob); }; URL.revokeObjectURL = (url) => { window.__q2B8BlobMeta.revokeCount += 1; return revoke(url); }; }, failOnce); }
async function download(page, id) { const button = page.getByRole("button", { name: "보드 백업 ZIP 다운로드" }); await expect(button).toBeEnabled(); const event = page.waitForEvent("download"); await button.click(); const item = await event; expect(await item.failure()).toBeNull(); const filename = item.suggestedFilename(); expect(filename).toMatch(/^gomdory-board-(?:.+-\d{4}-\d{2}-\d{2}|backup-\d{4}-\d{2}-\d{2})\.zip$/); const directory = path.join(out, "playwright-output", id, "downloads"); await fs.mkdir(directory, { recursive: true }); const target = path.join(directory, filename); await item.saveAs(target); const bytes = await fs.readFile(target); expect(bytes.byteLength).toBeGreaterThan(0); expect(bytes.readUInt32LE(0)).toBe(0x04034b50); await expect(page.getByRole("status")).toContainText("백업 파일 다운로드를 시작했습니다."); await expect(button).toBeEnabled(); return { filename, bytes, meta: await page.evaluate(() => window.__q2B8BlobMeta), download: { path: path.relative(path.dirname(out), target), sizeBytes: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex"), filename } }; }
test.beforeEach(async ({ context, page }) => { await context.route("**/*", async (route) => { const url = new URL(route.request().url()); if (url.origin === new URL(base).origin) return route.continue({ headers: { ...route.request().headers(), ...auth() } }); return route.abort(); }); });
test("B8-S1 actual local board backup download", async ({ page }) => { await instrument(page); await reset(page); await openBackup(page); const result = await download(page, "B8-S1"); expect(result.meta.type).toBe("application/zip"); await writeEvidence("B8-S1", { download: result.download, contract: { downloadButtonVisible: true, downloadButtonEnabled: true, downloadEventCount: 1, suggestedFilename: result.filename, blobMimeType: result.meta.type, blobSizeBytes: result.meta.size, createObjectUrlCount: result.meta.createCount, revokeObjectUrlCount: result.meta.revokeCount }, telemetry: { externalRequests: 0 } }); });
test("B8-S2 ZIP structure and representative files reopen", async ({ page }) => { await instrument(page); await reset(page); await openBackup(page); const result = await download(page, "B8-S2"); const entries = readStoredZip(result.bytes); expect([...entries.keys()].sort()).toEqual(["gomdory-board-backup/README.txt", "gomdory-board-backup/attachments-manifest.json", "gomdory-board-backup/board.json"]); const board = JSON.parse(new TextDecoder().decode(entries.get("gomdory-board-backup/board.json"))); const manifest = JSON.parse(new TextDecoder().decode(entries.get("gomdory-board-backup/attachments-manifest.json"))); const readme = new TextDecoder("utf-8", { fatal: true }).decode(entries.get("gomdory-board-backup/README.txt")); expect([board.board.sectionCount, board.board.cardCount, board.board.attachmentCount]).toEqual([2, 3, 1]); expect(manifest).toHaveLength(1); expect(readme).toContain("실제 이미지, 문서, 영상, 음악 파일은 ZIP에 포함되지 않습니다"); await writeEvidence("B8-S2", { download: result.download, contract: { zipSignatureValid: true, zipEntryCount: entries.size, zipEntryNames: [...entries.keys()], boardJsonParsed: true, manifestParsed: true, readmeDecoded: true, sectionCount: 2, cardCount: 3, attachmentCount: 1, hiddenCardCount: 1, coloredCardCount: 2 }, telemetry: { externalRequests: 0 } }); });
test("B8-S3 failed object URL has no false success and explicit retry works", async ({ page }) => { await instrument(page, true); await reset(page); await openBackup(page); const button = page.getByRole("button", { name: "보드 백업 ZIP 다운로드" }); let events = 0; page.on("download", () => { events += 1; }); await button.click(); await expect(page.getByRole("alert").filter({ hasText: "보드 백업 파일을 만들지 못했습니다." })).toBeVisible(); await expect(page.getByRole("status")).toHaveCount(0); const result = await download(page, "B8-S3"); expect(events).toBe(1); await writeEvidence("B8-S3", { download: result.download, contract: { failureDownloadEventCount: 0, falseSuccessShown: false, failureMessageShown: true, retryDownloadSucceeded: true }, telemetry: { externalRequests: 0 } }); });
test("B8-S4 local download is Drive-independent and unauthorized UI is absent", async ({ browser, page }) => { await instrument(page); await reset(page); await openBackup(page); expect(await page.evaluate(() => Boolean(window.google))).toBeFalsy(); const result = await download(page, "B8-S4"); const zipText = new TextDecoder().decode(result.bytes); expect(zipText).not.toContain(token); const unauthorized = await browser.newContext(); const denied = await unauthorized.newPage(); await denied.goto(`${base}/dashboard/boards/${boardId}/board`); await expect(denied.getByRole("button", { name: "보드 백업 ZIP 다운로드" })).toHaveCount(0); await unauthorized.close(); await writeEvidence("B8-S4", { download: result.download, contract: { localDownloadWithoutDrive: true, unauthorizedPanelAbsent: true, studentPanelAbsent: true, secretLeakage: false }, telemetry: { externalRequests: 0 } }); });
