// This file is auto-generated by scripts/contracts/generate.mjs. Do not edit.

import { api } from "@/lib/contracts/api";
import type { ContractRoute } from "@/lib/contracts/defineRoute";
import { apiFetch } from "@/lib/http/apiFetch";
import { apiPath, type ApiPath } from "@/lib/standards/pathTypes";
import { z } from "zod";

type CallOptions = RequestInit & { validate?: boolean };

type ResponseOf<T extends ContractRoute> = T["responseType"] extends "response" ? Response : z.infer<T["response"]>;

const shouldValidate = (options?: CallOptions) =>
  options?.validate ?? (process.env.NODE_ENV !== "production" || Boolean(process.env.CI));

const buildPath = (route: ContractRoute, params?: Record<string, unknown>) => {
  const args = (route.params ?? []).map((name) => params?.[name]);
  if ((route.params ?? []).some((_, index) => typeof args[index] === "undefined")) {
    throw new Error(`Missing params for route ${route.pathTemplate ?? route.path}`);
  }
  return route.buildPath(...args);
};

const appendQuery = (path: ApiPath, query?: Record<string, unknown>) => {
  if (!query) return path;
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      value.forEach((item) => search.append(key, String(item)));
    } else {
      search.append(key, String(value));
    }
  }
  const suffix = search.toString();
  return apiPath(suffix ? `${path}?${suffix}` : path);
};

const normalizeBody = (body: unknown, headers: Headers) => {
  if (body === undefined) return undefined;
  if (body instanceof FormData || body instanceof Blob || typeof body === "string") return body;
  headers.set("content-type", "application/json");
  return JSON.stringify(body);
};

const callRoute = async <T extends ContractRoute>(route: T, input?: z.input<T["request"]>, options?: CallOptions) => {
  if (shouldValidate(options)) {
    route.request.parse(input);
  }

  const payload = (input ?? {}) as { params?: Record<string, unknown>; query?: Record<string, unknown>; body?: unknown };
  const path = appendQuery(buildPath(route, payload.params), payload.query);
  const headers = new Headers(options?.headers ?? {});
  const body = normalizeBody(payload.body, headers);
  const response = await apiFetch(path, {
    ...options,
    method: route.method,
    headers,
    body,
  });
  if (route.responseType === "response") {
    return response as ResponseOf<T>;
  }
  const data = await response.json().catch(() => null);
  if (shouldValidate(options)) {
    route.response.parse(data);
  }
  return data as ResponseOf<T>;
};

export const client = {
  billing: {
  plan: { call: (input?: z.input<typeof api.billing.plan.request>, options?: CallOptions) => callRoute(api.billing.plan, input, options) },
  },
  coupons: {
  redeem: { call: (input?: z.input<typeof api.coupons.redeem.request>, options?: CallOptions) => callRoute(api.coupons.redeem, input, options) },
  },
  onboarding: {
  demo: { call: (input?: z.input<typeof api.onboarding.demo.request>, options?: CallOptions) => callRoute(api.onboarding.demo, input, options) },
  },
  templates: {
  publish: { call: (input?: z.input<typeof api.templates.publish.request>, options?: CallOptions) => callRoute(api.templates.publish, input, options) },
  },
  dashboard: {
  boards: {
  list: { call: (input?: z.input<typeof api.dashboard.boards.list.request>, options?: CallOptions) => callRoute(api.dashboard.boards.list, input, options) },
  create: { call: (input?: z.input<typeof api.dashboard.boards.create.request>, options?: CallOptions) => callRoute(api.dashboard.boards.create, input, options) },
  },
  },
  files: {
  list: { call: (input?: z.input<typeof api.files.list.request>, options?: CallOptions) => callRoute(api.files.list, input, options) },
  update: { call: (input?: z.input<typeof api.files.update.request>, options?: CallOptions) => callRoute(api.files.update, input, options) },
  remove: { call: (input?: z.input<typeof api.files.remove.request>, options?: CallOptions) => callRoute(api.files.remove, input, options) },
  view: { call: (input?: z.input<typeof api.files.view.request>, options?: CallOptions) => callRoute(api.files.view, input, options) },
  tagsSuggest: { call: (input?: z.input<typeof api.files.tagsSuggest.request>, options?: CallOptions) => callRoute(api.files.tagsSuggest, input, options) },
  tagsUpdate: { call: (input?: z.input<typeof api.files.tagsUpdate.request>, options?: CallOptions) => callRoute(api.files.tagsUpdate, input, options) },
  },
  ops: {
  whoami: { call: (input?: z.input<typeof api.ops.whoami.request>, options?: CallOptions) => callRoute(api.ops.whoami, input, options) },
  diagRequest: { call: (input?: z.input<typeof api.ops.diagRequest.request>, options?: CallOptions) => callRoute(api.ops.diagRequest, input, options) },
  notFoundAlert: { call: (input?: z.input<typeof api.ops.notFoundAlert.request>, options?: CallOptions) => callRoute(api.ops.notFoundAlert, input, options) },
  notFoundBrokenLinks: { call: (input?: z.input<typeof api.ops.notFoundBrokenLinks.request>, options?: CallOptions) => callRoute(api.ops.notFoundBrokenLinks, input, options) },
  notFoundBrokenLinksBundle: { call: (input?: z.input<typeof api.ops.notFoundBrokenLinksBundle.request>, options?: CallOptions) => callRoute(api.ops.notFoundBrokenLinksBundle, input, options) },
  },
  opsAdmin: {
  users: { call: (input?: z.input<typeof api.opsAdmin.users.request>, options?: CallOptions) => callRoute(api.opsAdmin.users, input, options) },
  storage: {
  quotaUpdate: { call: (input?: z.input<typeof api.opsAdmin.storage.quotaUpdate.request>, options?: CallOptions) => callRoute(api.opsAdmin.storage.quotaUpdate, input, options) },
  },
  coupons: {
  create: { call: (input?: z.input<typeof api.opsAdmin.coupons.create.request>, options?: CallOptions) => callRoute(api.opsAdmin.coupons.create, input, options) },
  list: { call: (input?: z.input<typeof api.opsAdmin.coupons.list.request>, options?: CallOptions) => callRoute(api.opsAdmin.coupons.list, input, options) },
  },
  },
  share: {
  filesDownload: { call: (input?: z.input<typeof api.share.filesDownload.request>, options?: CallOptions) => callRoute(api.share.filesDownload, input, options) },
  },
  showcases: {
  rotateToken: { call: (input?: z.input<typeof api.showcases.rotateToken.request>, options?: CallOptions) => callRoute(api.showcases.rotateToken, input, options) },
  revoke: { call: (input?: z.input<typeof api.showcases.revoke.request>, options?: CallOptions) => callRoute(api.showcases.revoke, input, options) },
  },
  boards: {
  liveGet: { call: (input?: z.input<typeof api.boards.liveGet.request>, options?: CallOptions) => callRoute(api.boards.liveGet, input, options) },
  livePost: { call: (input?: z.input<typeof api.boards.livePost.request>, options?: CallOptions) => callRoute(api.boards.livePost, input, options) },
  shareEnsure: { call: (input?: z.input<typeof api.boards.shareEnsure.request>, options?: CallOptions) => callRoute(api.boards.shareEnsure, input, options) },
  hudSettings: { call: (input?: z.input<typeof api.boards.hudSettings.request>, options?: CallOptions) => callRoute(api.boards.hudSettings, input, options) },
  showcaseEnsure: { call: (input?: z.input<typeof api.boards.showcaseEnsure.request>, options?: CallOptions) => callRoute(api.boards.showcaseEnsure, input, options) },
  triageList: { call: (input?: z.input<typeof api.boards.triageList.request>, options?: CallOptions) => callRoute(api.boards.triageList, input, options) },
  triageAction: { call: (input?: z.input<typeof api.boards.triageAction.request>, options?: CallOptions) => callRoute(api.boards.triageAction, input, options) },
  },
  s: {
  requests: {
  list: { call: (input?: z.input<typeof api.s.requests.list.request>, options?: CallOptions) => callRoute(api.s.requests.list, input, options) },
  create: { call: (input?: z.input<typeof api.s.requests.create.request>, options?: CallOptions) => callRoute(api.s.requests.create, input, options) },
  },
  },
} as const;