export const EDU_TABLES = {
  classes: "edu_classes",
  joinCodes: "edu_join_codes",
  joinSessions: "edu_join_sessions",
  lessonAttendanceDaily: "edu_lesson_attendance_daily",
  lessonCompletionsDaily: "edu_lesson_completions_daily",
  presentationLinks: "edu_presentation_links",
  presentationSettings: "edu_presentation_settings",
  featuredProjects: "edu_featured_projects",
  gallery: "edu_gallery",
  projects: "edu_projects",
  projectStats: "edu_project_stats",
  projectFeedback: "edu_project_feedback",
  projectVisibility: "edu_project_visibility",
} as const;

export const EDU_COLUMNS = {
  autoplayDefault: "autoplay_default",
  authorName: "author_name",
  boardId: "board_id",
  code: "code",
  codeHash: "code_hash",
  classCode: "class_code",
  createdAt: "created_at",
  dayBucket: "day_bucket",
  expiresAt: "expires_at",
  hidden: "hidden",
  hiddenReason: "hidden_reason",
  isActive: "is_active",
  intervalSecDefault: "interval_sec_default",
  lastUsedAt: "last_used_at",
  lessonId: "lesson_id",
  lessonKey: "lesson_key",
  nickname: "nickname",
  participantSubjectHash: "participant_subject_hash",
  anonHashes: "anon_hashes",
  uniqueAnonCount: "unique_anon_count",
  revokedAt: "revoked_at",
  shareCode: "share_code",
  slug: "slug",
  sortOrder: "sort_order",
  startMode: "start_mode",
  startSlug: "start_slug",
  token: "token",
  updatedAt: "updated_at",
  updatedBy: "updated_by",
  viewId: "view_id",
  viewCount: "view_count",
  previewUrl: "preview_url",
} as const;

export const EDU_RPC = {
  boardRole: "board_role",
} as const;
