export const PUBLIC_FLAGS_REGISTRY = [
  {
    flagName: "NEXT_PUBLIC_MARKETING_MISSION_DEMO_V1",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="marketing-mission-demo-v1-enabled"',
    domMarkerOff: 'data-testid="marketing-mission-demo-v1-disabled"',
    smokePath: "/",
    snapshotMeaning: "랜딩 20초 미션형 데모(Collect → Organize → Present) UI 노출",
  },
  {
    flagName: "NEXT_PUBLIC_COMMUNITY_3D_GALLERY",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="community-3d-gallery-enabled"',
    domMarkerOff: 'data-testid="community-3d-gallery-disabled"',
    smokePath: "/community/gallery-3d",
    snapshotMeaning: "커뮤니티 3D 갤러리 공개 화면 노출",
  },
  {
    flagName: "NEXT_PUBLIC_DASHBOARD_HINTS_V1",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="dashboard-hints-v1-enabled"',
    domMarkerOff: 'data-testid="dashboard-hints-v1-disabled"',
    smokePath: "/dashboard",
    snapshotMeaning: "Dashboard 상단 UX 힌트/코치마크 노출",
  },
  {
    flagName: "NEXT_PUBLIC_DASHBOARD_HOME_CARDS_V1",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="dashboard-home-cards-v1-enabled"',
    domMarkerOff: 'data-testid="dashboard-home-cards-v1-disabled"',
    smokePath: "/dashboard",
    snapshotMeaning: "Dashboard 홈 cards v1 섹션 노출",
  },
  {
    flagName: "NEXT_PUBLIC_DASHBOARD_HOME_HUB_V2",
    wave: 2,
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="dashboard-home-hub-v2"',
    domMarkerOff: 'data-testid="dashboard-home-hub-v2-disabled"',
    smokePath: "/dashboard",
    snapshotMeaning: "Dashboard 홈 Home Hub v2 섹션 노출",
  },
  {
    flagName: "NEXT_PUBLIC_DASHBOARD_CUSTOM_PAGE_RENDER_V1",
    wave: 2,
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="dashboard-custom-page-render-v1-enabled"',
    domMarkerOff: 'data-testid="dashboard-custom-page-render-v1-disabled"',
    smokePath: "/dashboard/me",
    snapshotMeaning: "Dashboard 내 커스텀 페이지 렌더 v1 노출",
  },
  {
    flagName: "NEXT_PUBLIC_DASHBOARD_CUSTOM_PAGES_V2",
    wave: 2,
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="dashboard-custom-pages-v2-enabled"',
    domMarkerOff: 'data-testid="dashboard-custom-pages-v2-disabled"',
    smokePath: "/dashboard/settings/customize",
    snapshotMeaning: "Dashboard 커스텀 페이지 v2 편집/목록 UI 노출",
  },
  {
    flagName: "NEXT_PUBLIC_LABS_TERMINAL",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="labs-terminal-enabled"',
    domMarkerOff: 'data-testid="labs-terminal-disabled"',
    smokePath: "/labs/terminal",
    snapshotMeaning: "Labs 터미널 실험 페이지 노출",
  },
  {
    flagName: "NEXT_PUBLIC_LABS_VR_WORLD",
    enabledWhen: "=== '1'",
    domMarkerOn: 'data-testid="labs-vr-world-enabled"',
    domMarkerOff: 'data-testid="labs-vr-world-disabled"',
    smokePath: "/labs/world",
    snapshotMeaning: "Labs VR/WebXR 실험 페이지 노출",
  },

];
